### ISSUE TITLE
Add tests for demo

### ISSUE THREAD

**Issue by joozek78** [Palindrom/palindrom-client#21]
Currently demo has no tests and can break without us knowing that. Only people who wanted to see our cool demo will notice
1. add tests
2. make sure they are run on travis

**Comment by warpech** [comment]
Frozen until we decide about https://github.com/Palindrom/Palindrom/issues/205

**Comment by warpech** [comment]
Closing as it was decided in https://github.com/Palindrom/Palindrom/issues/205 that the demos should be removed.

Opened a new issue: https://github.com/Palindrom/palindrom-client/issues/68
