### ISSUE TITLE
Use better timeouts in tests

### ISSUE THREAD

**Issue by joozek78** [Palindrom/palindrom-client#23]
## Problem statement

Currently all tests that use polymer have no way of finding out when exactly polymer has finished working with dom. Hence tests use timeout (100ms) which is prone to race conditions. Currently it's done like that:

``` js
puppetChange(puppet, [operationObject('replace', '/author/first', 'tomalec')]);
setTimeout(function listener() {
    expect(patchAppliedEventCallback).to.have.been.called;
    expect(document.querySelector("span").innerHTML).to.equal("tomalec");
    done();
    // temporary fix to alleviate race condition. 
}, 300);
```
## Proposed solutions

However it's not possible to properly wait for polymer operations end (it doesn't expose any event on that) we could copy selenium's solution which is at least better than current. It's a configurable wait function that sleeps in a loop for a maximal amount of time. It'd be used like that:

``` js
puppetChange(puppet, [operationObject('replace', '/author/first', 'tomalec')]);
var wait = configureWait(seconds(10), milliseconds(100)); // will throw after 10 seconds, but will check condition in 100ms intervals
wait.until(() => { // condition
    return document.querySelector("span").innerHTML == "tomalec";},
() => { // continuation
    expect(patchAppliedEventCallback).to.have.been.called; // if dom has already been modified, then puppet surely must have been called too
    done();
});
```

_We can't_ use (vanilla) stubs instead of sinon spies and use them to detect condition. We could only observe puppet's events, but not those from polymer (again, it has no events). This would look like this:

``` js
// won't work
var patchAppliedEventCallback = () => {
    expect(document.querySelector("span").innerHTML).to.equal("tomalec");
    done();
}
ppclient.addEventListener('patch-applied', patchAppliedEventCallback);
// change model
puppetChange(puppet, [operationObject('replace', '/author/first', 'tomalec')]);
```

**Comment by joozek78** [comment]
cc @warpech @tomalec

**Comment by tomalec** [comment]
I do agree that current solution with `setTimeout` is ugly, and I 'd like to change it as well.

However, I do not see how you proposed solution could work, as in terms of timing, it does exactly same thing as `ppclient.addEventListener('patch-applied',...)`.
Needless to say that `setTimeout` and `addEventListener('patch-applied` versions are way shorter and cleaner.

If by problematic "race condition" you mean `setTimeout`/`patch-applied` event racing with Polymer rendering, your proposition also have it. With `wait.until` it's even bigger than with `setTimeout` - timeline looks as follows:
puppetChange -> trigger Polymer Change -> trigger patch-applied -> any async (array/dom-if related) change may happen here.

----

The really clean solution would be to introduce events/callback/promises in Polymer binding.

As a workaround we could have today I would suggest something like:

```js
var patchAppliedEvent = sinon.spy().called.promise;
ppclient.addEventListener('patch-applied', patchAppliedEvent );
// change model
puppetChange(puppet, [operationObject('replace', '/author/first', 'tomalec')]);

patchAppliedEvent.should.be.eventually.called;
patchAppliedEvent.should.be.fulfilled.then(()=>setTimeout(()=>
  document.querySelector("span").innerHTML.should.equal("tomalec");
)).should.notify(done);
```
 
So we will:
- use Promises to improve readability of flow
- use vanilla `setTimeout` but to wait for Polymer only, after puppet triggered event => after it triggered Polymer change

It's not the perfect solution, and we still have a race between Polymer rendering and assertion, but at least this time `setTimeout` and Polymer started at same point.

**Comment by joozek78** [comment]
I made a minor (or major depending on who you ask) mistake in my example. I mean to wait (in condition part) for anything we need to wait for (in this case it should be dom change, not puppet event). I corrected my code in OP

**Comment by warpech** [comment]
@alshakero reports that this can be closed because it was fixed with other fixes. Closing as done.

If possible, @alshakero please add more details about how it is solved.
