### ISSUE TITLE
Why don't we rename this to palindrom-client?

### ISSUE THREAD

**Issue by alshakero** [Palindrom/palindrom-client#60]
This repo name confused me when I first joined. And until now whenever I see 
```js
"palindrom-client": "Palindrom/palindrom-polymer-client#^5.0.0"
```
it takes me a second

Isn't 
```js
"palindrom-client": "^5.0.0"
```
 much nicer 😃 

WDYT @tomalec @warpech

**Comment by warpech** [comment]
It is fine for me.

Any suggestions what to do with https://github.com/Palindrom/puppet-client? Should we move that repo to StarcounterFreezer?

**Comment by alshakero** [comment]
That would be cool. [No body is depending on it](https://github.com/Palindrom/puppet-client/network/dependents).

**Comment by warpech** [comment]
Great! I have renamed `palindrom-polymer-client` to `palindrom-client` and moved `puppet-client` to StarcounterFreezer org.
