### ISSUE TITLE
When I press "Cancel reloading" ("Do not reload") the counter does not dissapear

### ISSUE THREAD

**Issue by warpech** [Palindrom/palindrom-client#62]
When I press "Cancel reloading" ("Do not reload") the counter does not disappear.

Expected: The counter, "Reload now" and "Cancel reloading" links should disappear when I click "Cancel reloading".

![2018-02-01 21_34_32-kitchensink](https://user-images.githubusercontent.com/566463/35701994-1a588e2a-0798-11e8-85e4-b70ade63d8e1.png)

**Comment by alshakero** [comment]
Released 6.0.0 and it fixes this. It will be in StarcounterClientFiles soon (2-3) days.
