### ISSUE TITLE
Tests are failing on master

### ISSUE THREAD

**Issue by alshakero** [Palindrom/palindrom-client#64]
If https://github.com/Palindrom/palindrom-client/pull/63 gets merge tests will be failing on master. I will fix them.

**Comment by warpech** [comment]
Tests were failing on master even before #63. See:

![image](https://user-images.githubusercontent.com/566463/36727962-643fc3a6-1bbf-11e8-807a-9a2395de6a4d.png)

Do you know how to fix that?

**Comment by warpech** [comment]
Ah, sorry, I did not notice that :(

**Comment by alshakero** [comment]
No problem at all.

**Comment by warpech** [comment]
The tests are now passing, thanks for fixing!
