### ISSUE TITLE
Demo and test pages are not working 

### ISSUE THREAD

**Issue by tomalec** [Palindrom/palindrom-client#65]
### Steps to reproduce
1. Open README https://github.com/Palindrom/palindrom-client,
2. Click "Check it live!" or "test suite"

#### Live Demo
https://palindrom.github.io/palindrom-polymer-client/demo
https://palindrom.github.io/palindrom-polymer-client/test

### Expected result
Demo page should be show

### Actual result
"Page not found" is shown.

### Browsers affected
all

cc @alshakero

**Comment by tomalec** [comment]
Even locally the demo does not work for me.

**Comment by warpech** [comment]
Frozen until we decide about https://github.com/Palindrom/Palindrom/issues/205

**Comment by warpech** [comment]
Closing as it was decided in https://github.com/Palindrom/Palindrom/issues/205 that the demos should be removed.

Opened a new issue: https://github.com/Palindrom/palindrom-client/issues/68
